clear all; close all;
A = imread('list_11.jpg');
A = im2double(rgb2gray(A));
figure(20); imshow(A,[]); pause;
%% A = A + 0.1*randn(size(A));
r1 = edge(A,'sobel');
figure(1); imshow(r1); pause;
A = A/max(A(:));
%% A = adapthisteq(A);
figure(21); imshow(A,[]); pause;
A = adapthisteq(A);
A = 1 - A;
A = imgaussfilt(A, 1.2);
[Gx,Gy]= imgradientxy(A, 'sobel');
%% figure(1); imshowpair(Gx, Gy, 'montage'); pause;
G = sqrt(Gx.^2 + Gy.^2);
%% figure(2); imshow(G); pause;
G = 1 - G;
%% figure(2); imshow(G);
[mA nA] = size(G);
A_sr = sum(G(:))/(mA*nA);
%G(G>0.2)=1;
BW = edge(G,'sobel');
G = 1 - G;
se = strel('disk', 11);
I = imdilate(G,se);
figure(3); imshow(I);
I = imerode(I, se);
figure(4); imshow(I); pause;
[counts,x] = imhist(I,16);
stem(x,counts);
T = otsuthresh(counts);
I = imbinarize(G,T);
I = filter2(fspecial('average',3),I);
I = medfilt2(I, [3 3]);
I(I<0.7)=0;
T = adaptthresh(I, 0.1);
I = imbinarize(I,T);
figure(14); imshow(I); pause;
I = imclose(I, se);
% I(I<0.7)=0;
figure(22); imshow(I); pause;
se = strel('disk', 12);
I = imdilate(I,se);
figure(23); imshow(I); pause;
se = strel('disk', 10);
I = imerode(I, se);
figure(24); imshow(I); pause;
se = strel('disk', 6);
I = imdilate(I,se);
se = strel('disk', 4);
I = imerode(I, se);
figure(25); imshow(I); pause;
I = imfill(I, 'holes');
I(I>0.5)=1;
figure(5); imshow(I); pause;
I = medfilt2(I,[23 23]);
figure(15); imshow(I); pause;
L = zeros(mA+2, nA+2);
L(2:mA+1, 2:nA+1)=I;
BW = edge(L,'sobel');
figure(6); imshow(BW);
row = 185; col = 547;
BOUND = bwtraceboundary(BW,[row, col],'N');
B     = complex(BOUND(:,1),BOUND(:,2));
B     = B - mean(B);
nB    = length(BOUND(:,1));
figure(7); plot(BOUND(:,1),BOUND(:,2),'k'); grid on; 
%% figure(8); plot(1:nB,BOUND(:,1),'b',1:nB,BOUND(:,2),'r'); grid on;
nfb  = length(B);
FBND = abs(fft([B' zeros(1,nfb)]));
FBND = abs(fft([B']));
nit  = length(FBND);
nit4 = round(nit/4);
FB0  = FBND;
% FB0 = FBND(2:end-1);
FB0 = FB0/max(FB0);
%% figure(9); stem(FB0(1:100)); grid on;